// <auto-generated />
using System;
using FlokAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlokAPI.Migrations
{
    [DbContext(typeof(FlokAPIContext))]
    [Migration("20260410174450_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FlokAPI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EmployeeRole")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FlokAPI.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("longtext");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "carlajohns@gmail.com",
                            Name = "Carla Johns",
                            PhoneNum = "618-452-8417"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "mcastillo@outlook.com",
                            Name = "Martin Castillo",
                            PhoneNum = "860-254-7331"
                        },
                        new
                        {
                            CustomerId = 3,
                            Email = "vincentcooper85@gmail.com",
                            Name = "Vincent Cooper",
                            PhoneNum = "841-318-9338"
                        },
                        new
                        {
                            CustomerId = 4,
                            Email = "cras.eget@protonmail.org",
                            Name = "Nora Olsen",
                            PhoneNum = "880-547-6442"
                        },
                        new
                        {
                            CustomerId = 5,
                            Email = "primis.in@yahoo.ca",
                            Name = "Sasha Roman",
                            PhoneNum = "686-168-5402"
                        },
                        new
                        {
                            CustomerId = 6,
                            Email = "sit.amet@outlook.com",
                            Name = "Erich Booker",
                            PhoneNum = "686-107-2226"
                        },
                        new
                        {
                            CustomerId = 7,
                            Email = "amet.consectetuer@protonmail.edu",
                            Name = "Philip Guzman",
                            PhoneNum = "231-874-7758"
                        },
                        new
                        {
                            CustomerId = 8,
                            Email = "mauris@google.net",
                            Name = "Tucker Wright",
                            PhoneNum = "823-205-3788"
                        },
                        new
                        {
                            CustomerId = 9,
                            Email = "jessmendoza@gmail.com",
                            Name = "Jessica Mendoza",
                            PhoneNum = "632-627-4811"
                        },
                        new
                        {
                            CustomerId = 10,
                            Email = "iaculis.nec@outlook.edu",
                            Name = "Kevin Holt",
                            PhoneNum = "277-175-1424"
                        });
                });

            modelBuilder.Entity("FlokAPI.Models.DetailingService", b =>
                {
                    b.Property<int>("DetailingServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetailerId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("DetailingServiceId");

                    b.HasIndex("DetailerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DetailingServices");
                });

            modelBuilder.Entity("FlokAPI.Models.RentalService", b =>
                {
                    b.Property<int>("RentalServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ReservationStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ServiceAgentId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("RentalServiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceAgentId");

                    b.HasIndex("VehicleId");

                    b.ToTable("RentalServices");
                });

            modelBuilder.Entity("FlokAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasColumnType("longtext");

                    b.Property<string>("ClassCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRented")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("longtext");

                    b.Property<string>("Make")
                        .HasColumnType("longtext");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("VIN")
                        .HasColumnType("longtext");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Class = "Standard",
                            ClassCode = "SCAR",
                            Color = "White",
                            IsRented = true,
                            LicensePlate = "OR732",
                            Make = "Honda",
                            Mileage = 32000,
                            Model = "Civic",
                            State = "OR",
                            VIN = "TH829472"
                        },
                        new
                        {
                            VehicleId = 2,
                            Class = "Standard",
                            ClassCode = "SCAR",
                            Color = "Black",
                            IsRented = false,
                            LicensePlate = "IL773",
                            Make = "Toyota",
                            Mileage = 18500,
                            Model = "Corolla",
                            State = "IL",
                            VIN = "SC232043"
                        },
                        new
                        {
                            VehicleId = 3,
                            Class = "Full-Size",
                            ClassCode = "FCAR",
                            Color = "Silver",
                            IsRented = false,
                            LicensePlate = "CO292",
                            Make = "Chevrolet",
                            Mileage = 45200,
                            Model = "Malibu",
                            State = "CO",
                            VIN = "ST212765"
                        },
                        new
                        {
                            VehicleId = 4,
                            Class = "Economy",
                            ClassCode = "ECAR",
                            Color = "Blue",
                            IsRented = true,
                            LicensePlate = "WA729",
                            Make = "Chevrolet",
                            Mileage = 27800,
                            Model = "Spark",
                            State = "WA",
                            VIN = "TK939284"
                        },
                        new
                        {
                            VehicleId = 5,
                            Class = "Luxury Convertible",
                            ClassCode = "LTAR",
                            Color = "Gray",
                            IsRented = false,
                            LicensePlate = "CA728",
                            Make = "BMW",
                            Mileage = 221,
                            Model = "4-Series",
                            State = "CA",
                            VIN = "SR563809"
                        },
                        new
                        {
                            VehicleId = 6,
                            Class = "Large Pickup",
                            ClassCode = "PPAR",
                            Color = "Red",
                            IsRented = false,
                            LicensePlate = "OR621",
                            Make = "Ford",
                            Mileage = 39500,
                            Model = "F-150",
                            State = "OR",
                            VIN = "LT281943"
                        },
                        new
                        {
                            VehicleId = 7,
                            Class = "Standard SUV",
                            ClassCode = "SFAR",
                            Color = "Black",
                            IsRented = false,
                            LicensePlate = "CA728",
                            Make = "Hyundai",
                            Mileage = 52000,
                            Model = "Santa Fe",
                            State = "CA",
                            VIN = "SR938384"
                        },
                        new
                        {
                            VehicleId = 8,
                            Class = "Intermediate SUV",
                            ClassCode = "IFAR",
                            Color = "White",
                            IsRented = false,
                            LicensePlate = "OR612",
                            Make = "Toyota",
                            Mileage = 29000,
                            Model = "Rav4",
                            State = "OR",
                            VIN = "LK291013"
                        },
                        new
                        {
                            VehicleId = 9,
                            Class = "Sport",
                            ClassCode = "SSAR",
                            Color = "Black",
                            IsRented = false,
                            LicensePlate = "OR212",
                            Make = "Dodge",
                            Mileage = 22100,
                            Model = "Challenger",
                            State = "OR",
                            VIN = "HG637920"
                        },
                        new
                        {
                            VehicleId = 10,
                            Class = "Small Pickup",
                            ClassCode = "SPAR",
                            Color = "White",
                            IsRented = false,
                            LicensePlate = "WA875",
                            Make = "Nissan",
                            Mileage = 3587,
                            Model = "Frontier",
                            State = "WA",
                            VIN = "RG587984"
                        },
                        new
                        {
                            VehicleId = 11,
                            Class = "Jeep Wrangler",
                            ClassCode = "FJAR",
                            Color = "Red",
                            IsRented = false,
                            LicensePlate = "CA212",
                            Make = "Jeep",
                            Mileage = 22587,
                            Model = "Wrangler",
                            State = "CA",
                            VIN = "TC627912"
                        },
                        new
                        {
                            VehicleId = 12,
                            Class = "Minivan",
                            ClassCode = "MVAR",
                            Color = "Gray",
                            IsRented = false,
                            LicensePlate = "OR973",
                            Make = "Chrysler",
                            Mileage = 12634,
                            Model = "Pacifica",
                            State = "OR",
                            VIN = "RR292721"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FlokAPI.Models.DetailingService", b =>
                {
                    b.HasOne("FlokAPI.Models.ApplicationUser", "Detailer")
                        .WithMany("JoinEntities")
                        .HasForeignKey("DetailerId");

                    b.HasOne("FlokAPI.Models.Vehicle", "Vehicle")
                        .WithMany("JoinEntities")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detailer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FlokAPI.Models.RentalService", b =>
                {
                    b.HasOne("FlokAPI.Models.Customer", "Customer")
                        .WithMany("RentalJoinEntities")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlokAPI.Models.ApplicationUser", "ServiceAgent")
                        .WithMany("RentalJoinEntities")
                        .HasForeignKey("ServiceAgentId");

                    b.HasOne("FlokAPI.Models.Vehicle", "Vehicle")
                        .WithMany("RentalJoinEntities")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ServiceAgent");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FlokAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FlokAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlokAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FlokAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlokAPI.Models.ApplicationUser", b =>
                {
                    b.Navigation("JoinEntities");

                    b.Navigation("RentalJoinEntities");
                });

            modelBuilder.Entity("FlokAPI.Models.Customer", b =>
                {
                    b.Navigation("RentalJoinEntities");
                });

            modelBuilder.Entity("FlokAPI.Models.Vehicle", b =>
                {
                    b.Navigation("JoinEntities");

                    b.Navigation("RentalJoinEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
